### ISSUE TITLE
[코멘트 요청 #1] CSS Flexbox item 배치

### ISSUE THREAD

**Issue by suns2131** [suns2131/skilled_week#1]
## 질문내용
Flexbox에서 제가 원하는 배치는 item은 중앙으로 정렬되도록하고 
item 추가 시 왼쪽에서부터 item이 배치되도록하고싶은데, 
item은 중앙기준부터 생성이 되어 배치됩니다. 
justify-content 의 값을 center가 아닌 start로 주게되면 item의 배치가 제가 생각했던 중앙의 위치가 아니게되는데 
어떻게 해야 item은 중앙기준으로 배치가 되도록하고 카드 추가시 왼쪽부터 배치되게 할수 있을까요? 
아래는 제가 사용했던 CSS 소스코드와 제가 하고싶었던 카드 배치에 대한 부분입니다.<br>
<strong>소스코드 </strong>
![image](https://user-images.githubusercontent.com/42165194/160983370-1e6ba687-242a-4f49-87d0-330ca5b0cfca.png)

<br>
<hr>
<strong>현재 카드아이템 배치</strong>

![22222](https://user-images.githubusercontent.com/42165194/160984895-2c0bd50a-a7b5-48e7-9fd2-dcf771db21dc.PNG)

<strong>하고싶었던 카드아이템 배치</strong>
![111111](https://user-images.githubusercontent.com/42165194/160984862-708e58ab-b438-4593-a8b4-135aa0895765.png)

**Comment by nemyung** [comment]
선식님 안녕하세요, 이번주 코멘트를 맡게된 오세명입니다. 답변 드립니다.

- 우선 저는 이런 뷰는 grid로 구성하는 편이에요. grid-tamplate-columns와 grid-auto-rows 프로퍼티를 통해 구현하고싶은 리스트 뷰를 만들 수 있을 것 같아요.
- flex-box 모듈로 구현하게된다면,  card_box에 껴있는 마진을 지우고 list_box에 gap으로 간격을 설정하며 place-content 프로퍼티는 제거할 것 같습니다.
- 이렇게 될 경우 wrap 때문에 빈 공간이 있기 때문에 디버깅을 좀 많이 하셔야 합니다.

뷰 정말 깔끔하고 이쁘네요! 좋은 프로젝트 잘 봤습니다. 좋은 주말 보내세요!

**Comment by suns2131** [comment]
감사합니다.
